### ISSUE TITLE
wavy can't right pasrse RIFX file

### ISSUE THREAD

**Issue by GeneKong** [acelletti/wavy#1]
> The RIFX file format is identical to the RIFF file format except that all values
> are in Motorola byte order.
> OFFSET              Count TYPE   Description
> 0000h                   4 char   ID='RIFX'
> 0004h                   1 dword  Block size. This size is the size of the block
> 								 controlled by the RIFX header.
> 								 ="BSZ"
> 0008h                   4 char   Format name.
> REFERENCE:DDJ0994
> SEE ALSO:RIFF

So all values need parse as bigendian include trunk value, but module didn't do this, so parse failed.

**Comment by GeneKong** [comment]
[test.zip](https://github.com/acelletti/wavy/files/3357547/test.zip)

**Comment by acelletti** [comment]
I have fixed the initial issue, but it seems that the file header might be incorrect:
```FormatInfo(wFormatTag=1, nChannels=1, nSamplesPerSec=2000, nAvgBytesPerSec=6000, nBlockAlign=3, wBitsPerSample=24)```

In the format header `nBlockAlign` should be 6 not 3.

Can you specify the origin of the file you attached to the ticket?

**Comment by acelletti** [comment]
I'm going to close the issue for now as this is quite old, I'll reopen if I get some more input.
